# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20151215_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_bidding_phrase',
        ),
        migrations.AddField(
            model_name='user',
            name='user_bidding_newphrase',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_bidding_oldphrase',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase_bidding_price',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase_bidding_user',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase_id',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase_number_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bidding_newprice',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bidding_oldprice',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number_id',
            field=models.IntegerField(default=0),
        ),
    ]
